
package ChucNang;
import model.TaiKhoan;
import conn.connection;
import static conn.connection.conn;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;

import model.TaiKhoanDAO;
public class QuanLyTaiKhoan extends javax.swing.JPanel {
    DefaultTableModel model;
    ArrayList<TaiKhoan> lstk = new ArrayList<>();
    public QuanLyTaiKhoan() throws SQLException {
        initComponents();
        showResult();
    }
        
    public void showResult() throws SQLException {
        String[] arr = { "ID", "Tên tài khoản", "Mật khẩu" , "Role"};
		
        model = new DefaultTableModel(arr,0);
      
        tbQuanLyTaiKhoan.removeAll();   
        try {
            Connection cn = (Connection)connection.conn();
            String sql = "select * from TaiKhoan";
            Statement st = (Statement)cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()) {
                Vector<String> vc = new Vector<>();
                vc.add(rs.getString("MaNguoiDung"));
                vc.add(rs.getString("TenNguoiDung"));
                vc.add(rs.getString("MatKhau"));
                vc.add(rs.getString("role"));
                
                model.addRow(vc);
            } 
            tbQuanLyTaiKhoan.setModel(model);
        } catch(Exception e) {
            e.printStackTrace();
        }
        
    }
    
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTenDangNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnAddAdmin = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbErr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuanLyTaiKhoan = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thông báo:");

        jLabel3.setText("Tên đăng nhập:");

        jLabel4.setText("Mật khẩu");

        jLabel5.setText("Chuc nang:");

        btnAddUser.setText("Thêm tài khoản người dùng");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnAddAdmin.setText("Thêm tài khoản quản trị");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lbErr.setForeground(new java.awt.Color(255, 51, 51));

        jLabel6.setText("ID:");

        tbQuanLyTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tai khoan", "Mat khau", "role"
            }
        ));
        tbQuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuanLyTaiKhoanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbQuanLyTaiKhoanMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuanLyTaiKhoan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddUser)
                                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(lbErr))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbErr)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUser)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAdmin)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbQuanLyTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuanLyTaiKhoanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbQuanLyTaiKhoanMouseClicked

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        try {
            // TODO add your handling code here:
            String username = tfTenDangNhap.getText();
            String password = tfMatKhau.getText();
            String id =tfID.getText();
            if (username.equals("") || password.equals("")) {
                lbErr.setText("*Khong duoc de trong");
            } else {
                TaiKhoanDAO dao = new TaiKhoanDAO();
                TaiKhoan x = new TaiKhoan(username, password);
//              
                if (dao.addAdmin(x) == 1) {
                    JOptionPane a = new JOptionPane("Add thanh cong");
                    jOptionPane1.showMessageDialog(null, "", "Them tai khoan thanh cong!", JOptionPane.INFORMATION_MESSAGE);
                    model.fireTableDataChanged();
                } else if (dao.addAdmin(x) == 0){
                    JOptionPane a = new JOptionPane("Them user that bai");
                    jOptionPane1.showMessageDialog(null, "", "Tai khoan da ton tai!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            showResult();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
       try {
            // TODO add your handling code here:
            String username = tfTenDangNhap.getText();
            String password = tfMatKhau.getText();
            String id = tfID.getText();
            if (username.equals("") || password.equals("")) {
                lbErr.setText("*Khong duoc de trong");
            } else {
                TaiKhoanDAO dao = new TaiKhoanDAO();
                TaiKhoan x = new TaiKhoan(username, password);
//              
                if (dao.addUser(x) == 1) {
                    lstk.add(x);
                    try {
                        FileOutputStream fout = new FileOutputStream("C:\\Users\\manh\\Data\\Mon hoc\\Java\\ProjectJava\\MainProject\\user.txt");
                        ObjectOutputStream oos = new ObjectOutputStream(fout);
                        oos.writeObject(lstk);
                    } catch(Exception e) {
                        e.printStackTrace();
                    }
                    
                    JOptionPane a = new JOptionPane("Add thanh cong");
                    jOptionPane1.showMessageDialog(null, "", "Them tai khoan thanh cong!", JOptionPane.INFORMATION_MESSAGE);
                    model.fireTableDataChanged();
                } else if (dao.addUser(x) == 0){
                    JOptionPane a = new JOptionPane("Them user that bai");
                    jOptionPane1.showMessageDialog(null, "", "Tai khoan da ton tai!", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            showResult();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void tbQuanLyTaiKhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuanLyTaiKhoanMousePressed
        // TODO add your handling code here:
        int row=tbQuanLyTaiKhoan.getSelectedRow();
        String id = tbQuanLyTaiKhoan.getModel().getValueAt(row, 0).toString();
        String uname = tbQuanLyTaiKhoan.getModel().getValueAt(row, 1).toString();
        String up = tbQuanLyTaiKhoan.getModel().getValueAt(row, 2).toString();
        
        tfID.setText(id);
        tfTenDangNhap.setText(uname);
        tfMatKhau.setText(up);
    }//GEN-LAST:event_tbQuanLyTaiKhoanMousePressed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        TaiKhoanDAO dao = new TaiKhoanDAO();
        String username = tfTenDangNhap.getText();
        String password = tfMatKhau.getText();
        TaiKhoan x = new TaiKhoan(username, password);
        
      
        
        if (dao.deleteAccount(x) == -1) {
            jOptionPane1.showMessageDialog(null, "Xoa tai khoan that bai!", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jOptionPane1.showMessageDialog(null, "Xoa tai khoan thanh cong!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        
        try {
            showResult();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        TaiKhoanDAO dao = new TaiKhoanDAO();
        String username = tfTenDangNhap.getText();
        String password = tfMatKhau.getText();
        TaiKhoan x = new TaiKhoan(username, password);
        
        if (dao.updateAccount(x) == -1) {
            jOptionPane1.showMessageDialog(null, "Sua tai khoan that bai, chi duoc sua mat khau!", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jOptionPane1.showMessageDialog(null, "Sua tai khoan thanh cong!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        
        try {
            showResult();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErr;
    private javax.swing.JTable tbQuanLyTaiKhoan;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfMatKhau;
    private javax.swing.JTextField tfTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
