/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DemoChuongTrinh;

import ChuyenManHinh.ChuyenManHinhController;
import ChuyenManHinh.DanhMucBean;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ChucNang.TrangChu;


public class DemoChuongTrinh extends javax.swing.JFrame {

    /**
     * Creates new form DemoChuongTrinh
     */
    public DemoChuongTrinh() {
        initComponents();
        DanhMuc();
        setLocationRelativeTo(null);
    }
    
    public void DanhMuc() {
        ChuyenManHinhController controller = new ChuyenManHinhController(TrangChu);
        controller.setView(PanelTrangChu, lbTrangChu);
        List<DanhMucBean> list = new ArrayList<>();
        list.add(new DanhMucBean("TrangChu", PanelTrangChu, lbTrangChu));
        list.add(new DanhMucBean("QuanLyHoSoThiSinh", panelQuanLyHoSoThiSinh, lbQuanLyHoSoThiSinh));
        list.add(new DanhMucBean("QuanLyTaiKhoan", panelQuanLyTaiKhoan, lbQuanLyTaiKhoan));
        list.add(new DanhMucBean("NhapDiem", panelNhapDiem, lbNhapDiem));
        list.add(new DanhMucBean("QuanLyKhoiDuThi", panelQuanLyKhoiDuThi, lbQuanLyKhoiDuThi));
        list.add(new DanhMucBean("ThiSinhTrungTuyen", panelThiSinhTrungTuyen, lbThiSinhTrungTuyen));
        list.add(new DanhMucBean("ThiSinhViPham", panelThiSinhViPham, lbThiSinhViPham));
        
        controller.SetEven(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PanelTrangChu = new javax.swing.JPanel();
        lbTrangChu = new javax.swing.JLabel();
        panelQuanLyHoSoThiSinh = new javax.swing.JPanel();
        lbQuanLyHoSoThiSinh = new javax.swing.JLabel();
        panelQuanLyTaiKhoan = new javax.swing.JPanel();
        lbQuanLyTaiKhoan = new javax.swing.JLabel();
        panelNhapDiem = new javax.swing.JPanel();
        lbNhapDiem = new javax.swing.JLabel();
        panelQuanLyKhoiDuThi = new javax.swing.JPanel();
        lbQuanLyKhoiDuThi = new javax.swing.JLabel();
        panelThiSinhTrungTuyen = new javax.swing.JPanel();
        lbThiSinhTrungTuyen = new javax.swing.JLabel();
        panelThiSinhViPham = new javax.swing.JPanel();
        lbThiSinhViPham = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TrangChu = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 0, 25));

        lbTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrangChu.setText("Trang chủ");
        lbTrangChu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelTrangChuLayout = new javax.swing.GroupLayout(PanelTrangChu);
        PanelTrangChu.setLayout(PanelTrangChuLayout);
        PanelTrangChuLayout.setHorizontalGroup(
            PanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        PanelTrangChuLayout.setVerticalGroup(
            PanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jPanel1.add(PanelTrangChu);

        lbQuanLyHoSoThiSinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbQuanLyHoSoThiSinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLyHoSoThiSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconmonstr-school-15-24.png"))); // NOI18N
        lbQuanLyHoSoThiSinh.setText("Quản lý hồ sơ thí sinh");

        javax.swing.GroupLayout panelQuanLyHoSoThiSinhLayout = new javax.swing.GroupLayout(panelQuanLyHoSoThiSinh);
        panelQuanLyHoSoThiSinh.setLayout(panelQuanLyHoSoThiSinhLayout);
        panelQuanLyHoSoThiSinhLayout.setHorizontalGroup(
            panelQuanLyHoSoThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuanLyHoSoThiSinhLayout.createSequentialGroup()
                .addComponent(lbQuanLyHoSoThiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelQuanLyHoSoThiSinhLayout.setVerticalGroup(
            panelQuanLyHoSoThiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyHoSoThiSinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbQuanLyHoSoThiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelQuanLyHoSoThiSinh);

        lbQuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbQuanLyTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconmonstr-id-card-21-24.png"))); // NOI18N
        lbQuanLyTaiKhoan.setText("Quản lý tài khoản");

        javax.swing.GroupLayout panelQuanLyTaiKhoanLayout = new javax.swing.GroupLayout(panelQuanLyTaiKhoan);
        panelQuanLyTaiKhoan.setLayout(panelQuanLyTaiKhoanLayout);
        panelQuanLyTaiKhoanLayout.setHorizontalGroup(
            panelQuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyTaiKhoanLayout.createSequentialGroup()
                .addComponent(lbQuanLyTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        panelQuanLyTaiKhoanLayout.setVerticalGroup(
            panelQuanLyTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQuanLyTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(panelQuanLyTaiKhoan);

        lbNhapDiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNhapDiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconmonstr-school-13-24.png"))); // NOI18N
        lbNhapDiem.setText("Nhập điểm hồ sơ");

        javax.swing.GroupLayout panelNhapDiemLayout = new javax.swing.GroupLayout(panelNhapDiem);
        panelNhapDiem.setLayout(panelNhapDiemLayout);
        panelNhapDiemLayout.setHorizontalGroup(
            panelNhapDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhapDiemLayout.createSequentialGroup()
                .addComponent(lbNhapDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        panelNhapDiemLayout.setVerticalGroup(
            panelNhapDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapDiemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbNhapDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelNhapDiem);

        lbQuanLyKhoiDuThi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbQuanLyKhoiDuThi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanLyKhoiDuThi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconmonstr-user-22-24.png"))); // NOI18N
        lbQuanLyKhoiDuThi.setText("Quản lý khối dự thi");

        javax.swing.GroupLayout panelQuanLyKhoiDuThiLayout = new javax.swing.GroupLayout(panelQuanLyKhoiDuThi);
        panelQuanLyKhoiDuThi.setLayout(panelQuanLyKhoiDuThiLayout);
        panelQuanLyKhoiDuThiLayout.setHorizontalGroup(
            panelQuanLyKhoiDuThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyKhoiDuThiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbQuanLyKhoiDuThi)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelQuanLyKhoiDuThiLayout.setVerticalGroup(
            panelQuanLyKhoiDuThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyKhoiDuThiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbQuanLyKhoiDuThi, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelQuanLyKhoiDuThi);

        lbThiSinhTrungTuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThiSinhTrungTuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThiSinhTrungTuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconmonstr-education-1-24.png"))); // NOI18N
        lbThiSinhTrungTuyen.setText("Thí sinh trúng tuyển");

        javax.swing.GroupLayout panelThiSinhTrungTuyenLayout = new javax.swing.GroupLayout(panelThiSinhTrungTuyen);
        panelThiSinhTrungTuyen.setLayout(panelThiSinhTrungTuyenLayout);
        panelThiSinhTrungTuyenLayout.setHorizontalGroup(
            panelThiSinhTrungTuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThiSinhTrungTuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThiSinhTrungTuyen)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelThiSinhTrungTuyenLayout.setVerticalGroup(
            panelThiSinhTrungTuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThiSinhTrungTuyenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThiSinhTrungTuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelThiSinhTrungTuyen);

        lbThiSinhViPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbThiSinhViPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconmonstr-x-mark-3-24.png"))); // NOI18N
        lbThiSinhViPham.setText("Thí sinh vi phạm");

        javax.swing.GroupLayout panelThiSinhViPhamLayout = new javax.swing.GroupLayout(panelThiSinhViPham);
        panelThiSinhViPham.setLayout(panelThiSinhViPhamLayout);
        panelThiSinhViPhamLayout.setHorizontalGroup(
            panelThiSinhViPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThiSinhViPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThiSinhViPham, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        panelThiSinhViPhamLayout.setVerticalGroup(
            panelThiSinhViPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbThiSinhViPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jPanel1.add(panelThiSinhViPham);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TrangChu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TrangChu.setPreferredSize(new java.awt.Dimension(1100, 580));

        javax.swing.GroupLayout TrangChuLayout = new javax.swing.GroupLayout(TrangChu);
        TrangChu.setLayout(TrangChuLayout);
        TrangChuLayout.setHorizontalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );
        TrangChuLayout.setVerticalGroup(
            TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTrangChu;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbNhapDiem;
    private javax.swing.JLabel lbQuanLyHoSoThiSinh;
    private javax.swing.JLabel lbQuanLyKhoiDuThi;
    private javax.swing.JLabel lbQuanLyTaiKhoan;
    private javax.swing.JLabel lbThiSinhTrungTuyen;
    private javax.swing.JLabel lbThiSinhViPham;
    private javax.swing.JLabel lbTrangChu;
    private javax.swing.JPanel panelNhapDiem;
    private javax.swing.JPanel panelQuanLyHoSoThiSinh;
    private javax.swing.JPanel panelQuanLyKhoiDuThi;
    private javax.swing.JPanel panelQuanLyTaiKhoan;
    private javax.swing.JPanel panelThiSinhTrungTuyen;
    private javax.swing.JPanel panelThiSinhViPham;
    // End of variables declaration//GEN-END:variables
}
